# Generated by Django 3.2.4 on 2021-08-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Structured_lease_payments',
            new_name='StructuredLeasePayments',
        ),
    ]
