# Generated by Django 3.2.4 on 2021-08-26 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0003_auto_20210825_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirer_email', models.EmailField(max_length=254)),
                ('deposit_amount', models.PositiveIntegerField()),
                ('deposit_term', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='depositrate',
            name='interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='depositrate',
            unique_together={('lender', 'product')},
        ),
    ]
