# Generated by Django 3.2.4 on 2021-08-28 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_depositoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositinquiry',
            name='inquiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
