# Generated by Django 3.2.4 on 2021-08-30 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_di_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='do',
            name='di',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AlterField(
            model_name='depositoffer',
            name='depositinquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.depositinquiry'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Di',
        ),
        migrations.DeleteModel(
            name='Do',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
