# Generated by Django 3.2.4 on 2021-08-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_albumapp_trackapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoffer',
            name='depositinquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositoffers', to='hub.depositinquiry'),
        ),
    ]
